language: node_js
node_js:
- node
before_install:
- npm install -g codecov
script:
- npm test
- codecov

before_deploy:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
